spring:
  application:
    name: gateway

  security:
    user:
      name: test_user
      password: test_pw

  cloud:
    gateway:
      routes:
      #Bank core system
      - id: bank-service-demo
        uri: lb://bank-service
        predicates:
          - Path=/bank-service/**

      #Web message
      - id: message-service
        uri: lb://message-service
        predicates:
          - Path=/message-service/**
server:
  port: 9000
  ssl:
    enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: test_server

slack:
  webportfolio:
    channel-name: slack_channel_name
    channel-id: test_channel
    bot-token: test_token

logging:
  level:
    root: DEBUG
    org:
      springframework:
        aop: DEBUG
redis:
  webportfolio:
    port: 6969
    server: localhost
    max-request: 5
    reset-time: 2 #In minute
  bank:
    max-request: 50
    reset-time: 2