spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true

  security:
    user:
      name: ${ACTUATOR_USER}
      password: ${ACTUATOR_PASSWORD}

  cloud:
    gateway:
      routes:
      #Bank core system
      - id: bank-service-demo
        uri: lb://bank-service
        predicates:
          - Path=/bank-service/**

      #Web message
      - id: message-service
        uri: lb://message-service
        predicates:
          - Path=/message-service/**
server:
  port: ${APP_PORT}

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER}

slack:
  webportfolio:
    channel-id: ${SLACK_PORTFOLIO_CHANNEL}
    bot-token: ${SLACK_PORTFOLIO_TOKEN}


logging:
  level:
    root: INFO
    org:
      springframework:
        aop: DEBUG
redis:
  webportfolio:
    port: 6379
    server: localhost
    max-request: 5
    reset-time: 1 #In minute
  bank:
    max-request: 50
    reset-time: 1